{
  "id": "CVE-2020-15701",
  "assigner": "security@ubuntu.com",
  "Published": "2020-08-06T21:15:11.67Z",
  "Modified": "2023-01-24T01:45:18.333Z",
  "last-modified": "2023-01-24T01:45:18.333Z",
  "summary": "An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 2.1,
  "exploitabilityScore": 3.9,
  "impactScore": 2.9,
  "cvss-vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "https://launchpad.net/bugs/1877023",
    "https://usn.ubuntu.com/4449-1",
    "https://usn.ubuntu.com/4449-1/",
    "https://usn.ubuntu.com/4449-2/"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-755",
  "vulnerable_configuration_cpe_2_2": []
}