{
  "id": "CVE-2017-5601",
  "assigner": "cve@mitre.org",
  "Published": "2017-01-27T21:59:08.413Z",
  "Modified": "2018-11-30T10:29:02.957Z",
  "last-modified": "2018-11-30T10:29:02.957Z",
  "summary": "An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 5.0,
  "exploitabilityScore": 10.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "references": [
    "http://www.securityfocus.com/bid/95837",
    "http://www.securitytracker.com/id/1037974",
    "https://github.com/libarchive/libarchive/commit/98dcbbf0bf4854bf987557e55e55fff7abbf3ea9",
    "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-125",
  "vulnerable_configuration_cpe_2_2": []
}