{
  "id": "CVE-2020-8192",
  "assigner": "support@hackerone.com",
  "Published": "2020-07-30T11:15:11.313Z",
  "Modified": "2020-08-06T16:46:22.86Z",
  "last-modified": "2020-08-06T16:46:22.86Z",
  "summary": "A denial of service vulnerability exists in Fastify v2.14.1 and v3.0.0-rc.4 that allows a malicious user to trigger resource exhaustion (when the allErrors option is used) with specially crafted schemas.",
  "access": {
    "authentication": "SINGLE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 4.0,
  "exploitabilityScore": 8.0,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
  "references": [
    "https://hackerone.com/reports/903521"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-400",
  "vulnerable_configuration_cpe_2_2": []
}