{
  "id": "CVE-2019-8397",
  "assigner": "cve@mitre.org",
  "Published": "2019-02-17T05:29:00.55Z",
  "Modified": "2019-02-19T20:04:33.377Z",
  "last-modified": "2019-02-19T20:04:33.377Z",
  "summary": "An issue was discovered in the HDF HDF5 1.10.4 library. There is an out of bounds read in the function H5T_close_real in H5T.c.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "NONE",
    "integrity": "NONE"
  },
  "cvss": 4.3,
  "exploitabilityScore": 8.6,
  "impactScore": 2.9,
  "cvss-vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
  "references": [
    "https://github.com/magicSwordsMan/PAAFS/tree/master/vul5"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-125",
  "vulnerable_configuration_cpe_2_2": []
}