{
  "id": "CVE-2021-38945",
  "assigner": "psirt@us.ibm.com",
  "Published": "2022-06-24T14:15:08.247Z",
  "Modified": "2022-10-28T20:32:36.09Z",
  "last-modified": "2022-10-28T20:32:36.09Z",
  "summary": "IBM Cognos Analytics 11.2.1, 11.2.0, and 11.1.7 could allow a remote attacker to upload arbitrary files, caused by improper content validation. IBM X-Force ID: 211238.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "NETWORK"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 7.5,
  "exploitabilityScore": 10.0,
  "impactScore": 6.4,
  "cvss-vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
  "references": [
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/211238",
    "https://security.netapp.com/advisory/ntap-20220729-0002/",
    "https://www.ibm.com/support/pages/node/6597241"
  ],
  "vulnerable_configuration": [
    "cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.6:*:*:*:*:*:*:*"
  ],
  "vulnerable_product": [
    "cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.1:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.2:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.3:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.4:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.5:*:*:*:*:*:*:*",
    "cpe:2.3:a:ibm:cognos_analytics:11.1.6:*:*:*:*:*:*:*"
  ],
  "vendors": [
    "ibm"
  ],
  "products": [
    "cognos_analytics"
  ],
  "vulnerable_product_stems": [
    "cpe:2.3:a:ibm:cognos_analytics"
  ],
  "vulnerable_configuration_stems": [
    "cpe:2.3:a:ibm:cognos_analytics"
  ],
  "cwe": "CWE-434",
  "vulnerable_configuration_cpe_2_2": []
}