{
  "id": "CVE-2020-12850",
  "assigner": "cve@mitre.org",
  "Published": "2020-06-11T00:15:10.65Z",
  "Modified": "2020-06-22T18:02:05.17Z",
  "last-modified": "2020-06-22T18:02:05.17Z",
  "summary": "The following vulnerability applies only to the Pydio Cells Enterprise OVF version 2.0.4. Prior versions of the Pydio Cells Enterprise OVF (such as version 2.0.3) have a looser policy restriction allowing the “pydio” user to execute any privileged command using sudo. In version 2.0.4 of the appliance, the user pydio is responsible for running all the services and binaries that are contained in the Pydio Cells web application package, such as mysqld, cells, among others. This user has privileges restricted to run those services and nothing more.",
  "access": {
    "authentication": "NONE",
    "complexity": "MEDIUM",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "COMPLETE",
    "confidentiality": "COMPLETE",
    "integrity": "COMPLETE"
  },
  "cvss": 6.9,
  "exploitabilityScore": 3.4,
  "impactScore": 10.0,
  "cvss-vector": "AV:L/AC:M/Au:N/C:C/I:C/A:C",
  "references": [
    "http://packetstormsecurity.com/files/158002/Pydio-Cells-2.0.4-XSS-File-Write-Code-Execution.html",
    "https://www.coresecurity.com/advisories",
    "https://www.coresecurity.com/core-labs/advisories/pydio-cells-204-multiple-vulnerabilities"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-269",
  "vulnerable_configuration_cpe_2_2": []
}