{
  "id": "CVE-2018-7886",
  "assigner": "cve@mitre.org",
  "Published": "2018-03-15T01:29:00.23Z",
  "Modified": "2019-03-04T14:50:33.537Z",
  "last-modified": "2019-03-04T14:50:33.537Z",
  "summary": "An issue was discovered in CloudMe 1.11.0. An unauthenticated local attacker that can connect to the \"CloudMe Sync\" client application listening on 127.0.0.1 port 8888 can send a malicious payload causing a buffer overflow condition. This will result in code execution, as demonstrated by a TCP reverse shell, or a crash. NOTE: this vulnerability exists because of an incomplete fix for CVE-2018-6892.",
  "access": {
    "authentication": "NONE",
    "complexity": "LOW",
    "vector": "LOCAL"
  },
  "impact": {
    "availability": "PARTIAL",
    "confidentiality": "PARTIAL",
    "integrity": "PARTIAL"
  },
  "cvss": 4.6,
  "exploitabilityScore": 3.9,
  "impactScore": 6.4,
  "cvss-vector": "AV:L/AC:L/Au:N/C:P/I:P/A:P",
  "references": [
    "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/",
    "https://www.exploit-db.com/exploits/44470/"
  ],
  "vulnerable_configuration": [],
  "vulnerable_product": [],
  "vendors": [],
  "products": [],
  "vulnerable_product_stems": [],
  "vulnerable_configuration_stems": [],
  "cwe": "CWE-119",
  "vulnerable_configuration_cpe_2_2": []
}